- name: play1
  hosts: local
  connection: local
  tasks:
  - name: hello from play1 and task 1
    ansible.builtin.debug:
      msg: "Hello from paly 1 and task1"

  - name: hello from play1 and task 2
    ansible.builtin.debug:
      msg: "Hello from paly 1 and task2"

- name: play2
  hosts: local
  connection: local
  tasks:
  - name: hello from play2 and task 1
    ansible.builtin.debug:
      msg: "Hello from paly 2 and task1"

  - name: hello from play2 and task 2
    ansible.builtin.debug:
      msg: "Hello from paly 2 and task2"      