- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: please enter your name
    private: false




  
  - name: password
    prompt: please enter your password
    private: true

  tasks:
  - name: printing user information
    ansible.builtin.debug:
      msg:"Hello {{ username }}, {{ password }}"  

