- name: ansible datatypes
  hosts: local
  connection: local
  vars:
    duration: 120
    course: "devops"
    IS_LIVE: true
    tools: 
    - linux
    - shell
    - ansible
    concepts:
      ci: jenkins
      scripting: "shell,sndible,liinec,terrraform"

  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg:"{{ course }}, {{ duration }}, {{ IS_LIVE }}, {{ tools }}"
